---
title: "Thanks for visiting my blog!"
---

Growing up, I read stories of great adventurers and explorers. People who traveled to the ends of the earth, climbed the highest mountains, and sailed the seven seas. Marco Polo, Ibn Battuta, Zheng He. I was fascinated by their tales of discovery and adventure. I dreamed of one day embarking on my own great adventure, of seeing the world and experiencing all it had to offer.

Now that I'm older, I've set out to do just that. While most of my adult travels have been in Europe, I have now been to five continents. I hope that, in the near future I will be able to visit all seven. I have seen some of the most beautiful places on earth, met some of the most interesting people, and had some of the most amazing experiences.

This blog is largely a personal project, and I don't encourage you to rely on it as a primary resource. However, I am always pleased to answer questions or assist in travel planning, so if you'd like help, please feel free to reach out. I'm not hard to find. I hope you enjoy reading about my adventures as much as I enjoy having them. Thanks for visiting! 