---
title: "Brussels, Belgium"
---

Eat your sprouts.

```{r out.width='100%', echo=FALSE}
grandPlace <- paste("<b>Grand Place</b>")
atomium <- paste("<b>Atomium</b>")
bourse <- paste("<b>Bourse de Bruxelles</b>")
royalMuseum <- paste("<b>Royal Museum of Fine Arts</b>")
cathedral <- paste("<b>Cathedral of St. Michael and St. Gudula</b>")
royalPalace <- paste("<b>Royal Palace</b>")
leaflet() %>% addTiles() %>%
  setView(4.369656, 50.847048, zoom = 12) %>%
  addMarkers(4.352527, 50.846719, icon = greenDotIcon, popup = grandPlace) %>% # Grand Place
  addMarkers(4.341522, 50.894917, icon = greenDotIcon, popup = atomium) %>% # Atomium
  addMarkers(4.350168, 50.848112, icon = greenDotIcon, popup = bourse) %>% # Atomium
  addMarkers(4.358092, 50.841868, icon = greenDotIcon, popup = royalMuseum) %>% # Royal Museum of Fine Arts
  addMarkers(4.360082, 50.847838, icon = greenDotIcon, popup = cathedral) %>% # Cathedral of St. Michael and St. Gudula
  addMarkers(4.362264, 50.841923, icon = greenDotIcon, popup = royalPalace) # Royal Palace
```

Easily one of my top three cities worldwide, Paris is one of those places with an infinitude of things to do.

```{r echo = FALSE, results = 'asis'}
titles <- c("Length of Stay", "Transportation", "Major Sights","Unique Foods", "Restaurant Recommendations")
values <- c("One week, many long weekends", "7 hour flight from YYZ", "Atomium", "Trianon", "Angelina")
df <- data.frame(titles, values)
library(knitr)
kable(df, col.names = NULL)
```