---
title: "A Travel Blog for the Intrepid"
output:
  html_document:
    self_contained: false
---

Welcome! This is a repository for all sorts of pointers, tips, and useful information I have gathered from my adventures. 

Carpe diem

 ```{r, lazy=TRUE}
 library(rbokeh)
 figure(width = 800) %>%
   ly_points(date, Freq, data = flightfreq,
     hover = list(date, Freq, dow), size = 5) %>%
   ly_abline(v = as.Date("2001-09-11"))
 ```

```{r out.width='100%', echo=FALSE}
library(leaflet)
#Africa
#Morocco
essaouiraCont <- paste("<b><a href='./merzouga.html'>Essaouira, Morocco</a></b>")
marrakeshCont <- paste("<b><a href='./marrakesh.html'>Marrakesh, Morocco</a></b>")
merzougaCont <- paste("<b><a href='./merzouga.html'>Merzouga, Morocco</a></b>")
ouarzazateCont <- paste("<b><a href='./ouarzazate.html'>Ouarzazate, Morocco</a></b>")
#Europe
#Austria
viennaCont <- paste("<b><a href='./vienna.html'>Vienna, Austria</a></b>")
#Belgium
antwerpCont <- paste("<b><a href='./antwerp.html'>Antwerp, Belgium</a></b>")
brugesCont <- paste("<b><a href='./bruges.html'>Bruges, Belgium</a></b>")
brusselsCont <- paste("<b><a href='./brussels.html'>Brussels, Belgium</a></b>")
courtraiCont <- paste("<b><a href='./courtrai.html'>Courtrai, Belgium</a></b>")
ghentCont <- paste("<b><a href='./ghent.html'>Ghent, Belgium</a></b>")
ostendCont <- paste("<b><a href='./ostend.html'>Ostend, Belgium</a></b>")
tournaiCont <- paste("<b><a href='./tournai.html'>Tournai, Belgium</a></b>")
#Bosnia & Herzegovina 
mostarCont <- paste("<b><a href='./mostar.html'>Mostar, Bosnia & Herzegovina</a></b>")
#Croatia
dubrovnikCont <- paste("<b><a href='./dubrovnik.html'>Dubrovnik, Croatia</a></b>")
plitviceCont <- paste("<b><a href='./plitvice.html'>Plitvice Lakes, Croatia</a></b>")
splitCont <- paste("<b><a href='./split.html'>Split, Croatia</a></b>")
trogirCont <- paste("<b><a href='./trogir.html'>Trogir, Croatia</a></b>")
#France
avignonCont <- paste("<b><a href='./avignon.html'>Avignon, France</a></b>")
bayonneCont <- paste("<b><a href='./bayonne.html'>Bayonne, France</a></b>")
biarritzCont <- paste("<b><a href='./biarritz.html'>Biarritz, France</a></b>")
bordeauxCont <- paste("<b><a href='./bordeaux.html'>Bordeaux, France</a></b>")
carcassonneCont <- paste("<b><a href='./carcassonne.html'>Carcassonne, France</a></b>")
langonCont <- paste("<b><a href='./langon.html'>Langon, France</a></b>")
laRochelleCont <- paste("<b><a href='./la-rochelle.html'>La Rochelle, France</a></b>")
leHavreCont <- paste("<b><a href='./le-havre.html'>Le Havre, France</a></b>")
lilleCont <- paste("<b><a href='./lille.html'>Lille, France</a></b>")
montpellierCont <- paste("<b><a href='./montpellier.html'>Montpellier, France</a></b>")
msmCont <- paste("<b><a href='./mont-saint-michel.html'>Mont-Saint-Michel, France</a></b>")
nimesCont <- paste("<b><a href='./nimes.html'>Nîmes, France</a></b>")
saintEmilionCont <- paste("<b><a href='./saint-emilion.html'>Saint-Émilion, France</a></b>")
saintMaloCont <- paste("<b><a href='./saint-malo.html'>Saint-Malo, France</a></b>")
strasbourgCont <- paste("<b><a href='./strasbourg.html'>Strasbourg, France</a></b>")
toulouseCont <- paste("<b><a href='./toulouse.html'>Toulouse, France</a></b>")
#Greece
athensCont <- paste("<b><a href='./athens.html'>Athens, Greece</a></b>")
meteoraCont <- paste("<b><a href='./meteora.html'>Meteora, Greece</a></b>")
mykonosCont <- paste("<b><a href='./mykonos.html'>Mykonos, Greece</a></b>")
santoriniCont <- paste("<b><a href='./santorini.html'>Santorini, Greece</a></b>")
#Netherlands
amsterdamCont <- paste("<b><a href='./amsterdam.html'>Amsterdam, Netherlands</a></b>")
# Spain
bilbaoCont <- paste("<b><a href='./bilbao.html'>Bilbao, Spain</a></b>")
llanesCont <- paste("<b><a href='./llanes.html'>Llanes, Spain</a></b>")
lugoCont <- paste("<b><a href='./lugo.html'>Lugo, Spain</a></b>")
madridCont <- paste("<b><a href='./madrid.html'>Madrid, Spain</a></b>")
mallorcaCont <- paste("<b><a href='./mallorca.html'>Mallorca, Spain</a></b>")
oviedoCont <- paste("<b><a href='./oviedo.html'>Oviedo, Spain</a></b>")
sanSebastianCont <- paste("<b><a href='./san-sebastian.html'>San Sebastian, Spain</a></b>")
santanderCont <- paste("<b><a href='./santander.html'>Santander, Spain</a></b>")
santiagoDeCompostelaCont <- paste("<b><a href='./santiago-de-compostela.html'>Santiago de Compostela, Spain</a></b>")
#South America
#Peru
arequipaCont <- paste("<b><a href='./arequipa.html'>Arequipa, Peru</a></b>")
colcaCanyonCont <- paste("<b><a href='./colca-canyon.html'>Colca Canyon, Peru</a></b>")
huacachinaCont <- paste("<b><a href='./huacachina.html'>Huacachina, Peru</a></b>")
humantayCont <- paste("<b><a href='./humantay.html'>Laguna Humantay, Peru</a></b>")
limaCont <- paste("<b><a href='./lima.html'>Lima, Peru</a></b>")
machuPicchuCont <- paste("<b><a href='./machu-picchu.html'>Machu Picchu, Peru</a></b>")
marasCont <- paste("<b><a href='./maras.html'>Salineras de Maras, Peru</a></b>")
paracasCont <- paste("<b><a href='./paracas.html'>Paracas, Peru</a></b>")
pisacCont <- paste("<b><a href='./pisac.html'>Pisac, Peru</a></b>")
rainbowMountainCont <- paste("<b><a href='./rainbow-mountain.html'>Rainbow Mountain, Peru</a></b>")

greenDotIcon <- makeIcon(
  iconUrl = "images/GreenDot.png",
  iconWidth = 7, iconHeight = 7,
  iconAnchorX = 0, iconAnchorY = 0
)
leaflet() %>% addTiles() %>%
  setView(10.137634, 35.206355, zoom = 2) %>%
  # Africa
  # Morocco
  addMarkers(-9.765129, 31.508956, icon = greenDotIcon, popup = essaouiraCont) %>% # Essaouira, Morocco
  addMarkers(-7.987035, 31.627309, icon = greenDotIcon, popup = marrakeshCont) %>% # Marrakesh, Morocco
  addMarkers(-4.014088, 31.099917, icon = greenDotIcon, popup = merzougaCont) %>% # Merzouga, Morocco
  addMarkers(-6.919241, 30.924812, icon = greenDotIcon, popup = ouarzazateCont) %>% # Ouarzazate, Morocco
  # Europe
  #Austria
  addMarkers(16.3738, 48.2082, icon = greenDotIcon, popup = viennaCont) %>% # Vienna, Austria
  # Belgium
  addMarkers(4.4051, 51.2213, icon = greenDotIcon, popup = antwerpCont) %>% # Antwerp, Belgium
  addMarkers(3.7303, 51.0500, icon = greenDotIcon, popup = ghentCont) %>% # Ghent, Belgium
  addMarkers(3.2248, 51.2092, icon = greenDotIcon, popup = brugesCont) %>% # Bruges, Belgium
  addMarkers(4.3572, 50.8476, icon = greenDotIcon, popup = brusselsCont) %>% # Brussels, Belgium 
  addMarkers(3.2544, 50.8268, icon = greenDotIcon, popup = courtraiCont) %>% # Courtrai, Belgium
  addMarkers(2.920971, 51.228159, icon = greenDotIcon, popup = ostendCont) %>% # Ostend, Belgium
  addMarkers(3.385895, 50.608391, icon = greenDotIcon, popup = tournaiCont) %>% # Tournai, Belgium
  # Bosnia & Herzegovina
  addMarkers(17.8078, 43.3438, icon = greenDotIcon, popup = mostarCont) %>% # Mostar, Bosnia & Herzegovina
  # Croatia
  addMarkers(16.4435, 43.5147, icon = greenDotIcon, popup = splitCont) %>% # Split, Croatia
  addMarkers(15.5820, 44.8654, icon = greenDotIcon, popup = plitviceCont) %>% # Plitvice Lakes NP, Croatia
  addMarkers(18.0944, 42.6507, icon = greenDotIcon, popup = dubrovnikCont) %>% # Dubrovnik, Croatia
  addMarkers(16.2502, 43.5164, icon = greenDotIcon, popup = trogirCont) %>% # Trogir, Croatia
  # France
  addMarkers(4.833389, 43.941724, icon = greenDotIcon, popup = avignonCont) %>% # Avignon, France
  addMarkers(-1.4748, 43.4929, icon= greenDotIcon, popup = bayonneCont) %>% # Bayonne, France
  addMarkers(-1.5586, 43.4832, icon= greenDotIcon, popup = biarritzCont) %>% # Biarritz, France
  addMarkers(-0.5792, 44.8378, icon = greenDotIcon, popup = bordeauxCont) %>% # Bordeaux, France
  addMarkers(2.363749, 43.213072, icon = greenDotIcon, popup = carcassonneCont) %>% # Carcassonne, France
  addMarkers(-1.1511, 46.1603, icon= greenDotIcon, popup = laRochelleCont) %>% # La Rochelle, France
  addMarkers(0.1079, 49.4944, icon = greenDotIcon, popup = leHavreCont) %>% # Le Havre, France
  addMarkers(3.0573, 50.6292, icon= greenDotIcon, popup = lilleCont) %>% # Lille, France
  addMarkers(-0.2451, 44.5554, icon= greenDotIcon, popup = langonCont) %>% # Langon, France
  addMarkers(-1.5115, 48.6361, icon = greenDotIcon, popup = msmCont) %>% # Mont-Saint-Michel, France
  addMarkers(3.874190, 43.610049, icon = greenDotIcon, popup = montpellierCont) %>% # Montpellier, France
  addMarkers(4.352978, 43.839594, icon = greenDotIcon, popup = nimesCont) %>% # Nîmes, France
  addMarkers(2.3522, 48.8566, icon = greenDotIcon) %>% # Paris, France
  addMarkers(-0.1557, 44.8944, icon= greenDotIcon, popup = saintEmilionCont) %>% # Saint-Émilion, France
  addMarkers(-2.0257, 48.6493, icon= greenDotIcon, popup = saintMaloCont) %>% # Saint-Malo, France
  addMarkers(7.752149, 48.581851, icon = greenDotIcon, popup = strasbourgCont) %>% # Strasbourg, France
  addMarkers(1.4442, 43.6047, icon= greenDotIcon, popup = toulouseCont) %>% # Toulouse, France
  # Greece
  addMarkers(23.7275, 37.9838, icon = greenDotIcon, popup = athensCont) %>% # Athens, Greece
  addMarkers(21.635569, 39.713060, icon = greenDotIcon, popup = meteoraCont) %>% # Meteora, Greece
  addMarkers(25.295520, 37.444066, icon = greenDotIcon, popup = mykonosCont) %>% # Mykonos, Greece
  addMarkers(25.412546, 36.404867, icon = greenDotIcon, popup = santoriniCont) %>% # Santorini, Greece
  # Netherlands
  addMarkers(4.9041, 52.3676, icon = greenDotIcon, popup = amsterdamCont) %>% # Amsterdam, Netherlands
  # Spain
  addMarkers(-2.933283, 43.266939, icon = greenDotIcon, popup = bilbaoCont) %>% # Bilbao, Spain
  addMarkers(-4.754333, 43.419427, icon = greenDotIcon, popup = llanesCont) %>% # Llanes, Spain
  addMarkers(-7.553189, 43.020080, icon = greenDotIcon, popup = lugoCont) %>% # Lugo, Spain
  addMarkers(-3.7038, 40.4168, icon = greenDotIcon, popup = madridCont) %>% # Madrid, Spain
  addMarkers(-5.846400, 43.370833, icon = greenDotIcon, popup = oviedoCont) %>% # Oviedo, Spain
  addMarkers(2.648381, 39.569705, icon = greenDotIcon, popup = mallorcaCont) %>% # Mallorca, Spain
  addMarkers(-3.826139, 43.464668, icon = greenDotIcon, popup = santanderCont) %>% # Santander, Spain
  addMarkers(-8.5448, 42.8782, icon = greenDotIcon, popup = santiagoDeCompostelaCont) %>% # Santiago de Compostela, Spain
  addMarkers(-1.980055, 43.317613, icon = greenDotIcon, popup = sanSebastianCont) %>% # San Sebastian, Spain
  # Asia
  # Turkiye
  addMarkers(27.1799, 39.1214, icon = greenDotIcon) %>% # Bergama, Turkiye
  addMarkers(34.8289, 38.6431, icon = greenDotIcon) %>% # Goreme, Turkiye
  addMarkers(29.0610, 40.1885, icon = greenDotIcon) %>% # Bursa, Turkiye
  addMarkers(28.9784, 41.0082, icon = greenDotIcon) %>% # Istanbul, Turkiye
  # North America
  # Canada
  addMarkers(-75.6972, 45.4215, icon = greenDotIcon) %>% # Ottawa, Canada
  addMarkers(-73.5674, 45.5019, icon = greenDotIcon) %>% # Montreal, Canada
  addMarkers(-79.3832, 43.6532, icon = greenDotIcon) %>% # Toronto, Canada
  # Mexico
  addMarkers(-105.2965, 20.6986, icon = greenDotIcon) %>% # Puerto Vallarta, Mexico
  addMarkers(-105.4410, 20.8691, icon = greenDotIcon) %>% # Sayulita, Mexico
  # United States
  addMarkers(-74.0060, 40.7128, icon = greenDotIcon) %>% # New York, USA
  # South America
  # Peru
  addMarkers(-71.5375, -16.4090, icon = greenDotIcon, popup = arequipaCont) %>% # Arequipa, Peru
  addMarkers(-72.1771, -15.6574, icon = greenDotIcon, popup = colcaCanyonCont) %>% # Colca Canyon, Peru
  addMarkers(-75.7626, -14.0875, icon = greenDotIcon, popup = huacachinaCont) %>% # Huacachina, Peru
  addMarkers(-72.569038, -13.342497, icon = greenDotIcon, popup = humantayCont) %>% # Laguna Humantay, Peru
  addMarkers(-77.0428, -12.0464, icon = greenDotIcon, popup = limaCont) %>% # Lima, Peru
  addMarkers(-72.4973, -13.2263, icon = greenDotIcon, popup = machuPicchuCont) %>% # Machu Picchu, Peru
  addMarkers(-72.156615, -13.334900, icon = greenDotIcon, popup = marasCont) %>% # Salineras de Maras, Peru
  addMarkers(-76.2508, -13.8409, icon = greenDotIcon, popup = paracasCont) %>% # Paracas, Peru
  addMarkers(-71.850243, -13.421403, icon = greenDotIcon, popup = pisacCont) %>% # Pisac, Peru 
  addMarkers(-71.302818, -13.870390, icon = greenDotIcon, popup = rainbowMountainCont) # Rainbow Mountain, Peru
```


<h2>Africa</h2>
<hr class="rounded">
<h3>Morocco</h3>
```{r out.width='100%', echo=FALSE}
library(htmltools)
thumbnail <- function(title, img, href, caption = TRUE) {
  div(class = "col-sm-4",
      a(class = "thumbnail", title = title, href = href,
        img(src = img),
        div(class = if (caption) "caption",
            if (caption) title)
      )
  )
}
thumbnail("Essaouira, Morocco", "images/Essaouira/essaouira15.png", "./essaouira.html")
thumbnail("Marrakesh, Morocco", "images/Marrakesh/marrakesh.png", "./marrakesh.html")
thumbnail("Merzouga, Morocco", "images/Merzouga/merzouga37.png", "./merzouga.html")
thumbnail("Ouarzazate, Morocco", "images/Ouarzazate/ouarzazate28.png", "./ouarzazate.html")
``` 
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h2>Europe</h2>
<hr class="rounded">
<h3>Austria</h3>
```{r out.width='100%', echo=FALSE}
thumbnail("Vienna, Austria", "images/Vienna/vienna11.png", "./vienna.html")
``` 
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<hr class="dotted">
<h3>Belgium</h3>
```{r out.width='100%', echo=FALSE}
thumbnail("Antwerp, Belgium", "images/Antwerp/antwerp12.png", "./antwerp.html")
thumbnail("Bruges, Belgium", "images/Bruges/bruges25.png", "./bruges.html")
thumbnail("Brussels, Belgium", "images/Brussels/brussels9.png", "./brussels.html")
thumbnail("Courtrai, Belgium", "images/Courtrai/courtrai2.png", "./courtrai.html")
thumbnail("Ghent, Belgium", "images/Ghent/ghent8.png", "./ghent.html")
thumbnail("Ostend, Belgium", "images/Ostend/oostende.png", "./ostend.html")
thumbnail("Tournai, Belgium", "images/Tournai/tournai.png", "./tournai.html")
```
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<hr class="rounded">
<h3>Bosnia & Herzegovina</h3>
```{r out.width='100%', echo=FALSE}
thumbnail("Mostar, Bosnia & Herzegovina", "images/Mostar/mostar2.png", "./mostar.html")
```
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<hr class="dotted">
<h3>Croatia</h3>
```{r out.width='100%', echo=FALSE}
thumbnail("Dubrovnik, Croatia", "images/Dubrovnik/dubrovnik13.png", "./dubrovnik.html")
thumbnail("Plitvice Lakes, Croatia", "images/Plitvice/plitvice24.png", "./plitvice.html")
thumbnail("Split, Croatia", "images/split/split4.png", "./split.html")
thumbnail("Trogir, Croatia", "images/Trogir/trogir5.png", "./trogir.html")
```
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<hr class="dotted">
<h3>France</h3>
```{r out.width='100%', echo=FALSE}
thumbnail("Bayonne, France", "images/Bayonne/bayonne1.png", "./bayonne.html")
thumbnail("Biarritz, France", "images/Biarritz/biarritz7.png", "./biarritz.html")
thumbnail("Bordeaux, France", "images/Bordeaux/bordeaux2.png", "./bordeaux.html")
thumbnail("Langon, France", "images/Langon/langon8.png", "./langon.html")
thumbnail("La Rochelle, France", "images/LaRochelle/larochelle6.png", "./la-rochelle.html")
thumbnail("Le Havre, France", "images/LeHavre/lehavre2.png", "./le-havre.html")
thumbnail("Lille, France", "images/Lille/lille7.png", "./lille.html") 
thumbnail("Mont-Saint-Michel, France", "images/MontSaintMichel/msm1.png", "./mont-saint-michel.html")
thumbnail("Saint-Émilion, France", "images/SaintEmilion/saintemilion17.png", "./saint-emilion.html")
thumbnail("Saint-Malo, France", "images/SaintMalo/saintmalo49.png", "./saint-malo.html")
thumbnail("Toulouse, France", "images/Toulouse/toulouse19.png", "./toulouse.html")
```
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<hr class="dotted">
<h3>Greece</h3>
```{r out.width='100%', echo=FALSE}
thumbnail("Meteora, Greece", "images/Meteora/meteora24.png", "./meteora.html")
thumbnail("Mykonos, Greece", "images/Mykonos/mykonos20.png", "./mykonos.html")
thumbnail("Santorini, Greece", "images/Santorini/santorini71.png", "./santorini.html")
```
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<hr class="dotted">
<h3>Netherlands</h3>
```{r out.width='100%', echo=FALSE}
thumbnail("Amsterdam, Netherlands", "images/Amsterdam/amsterdam3.png", "./amsterdam.html")
```
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h2>South America</h2>
<hr class="rounded">
<h3>Peru</h3>
```{r out.width='100%', echo=FALSE}
thumbnail("Arequipa, Peru", "images/Arequipa/arequipa15.png", "./arequipa.html")
thumbnail("Colca Canyon, Peru", "images/ColcaCanyon/colca6.png", "./colca-canyon.html")
thumbnail("Huacachina, Peru", "images/Huacachina/huacachina44.png", "./huacachina.html")
thumbnail("Laguna Humantay, Peru", "images/Humantay/humantay16.png", "./humantay.html")
thumbnail("Lima, Peru", "images/Lima/lima11.png", "./lima.html")
thumbnail("Machu Picchu, Peru", "images/MachuPicchu/mp1.png", "./machu-picchu.html")
thumbnail("Salineras de Maras, Peru", "images/Maras/maras1.png", "./maras.html")
thumbnail("Paracas, Peru", "images/Paracas/paracas11.png", "./paracas.html")
thumbnail("Pisac, Peru", "images/Pisac/pisac10.png", "./pisac.html")
thumbnail("Rainbow Mountain, Peru", "images/RainbowMountain/rainbow20.png", "./rainbow-mountain.html")
```
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />