---
title: "Istanbul, Türkiye"
---

The Second Rome.

```{r out.width='100%', echo=FALSE}
hagiaSophia <- paste("<b>Hagia Sophia</b>")
topkapiPalace <- paste("<b>Topkapi Palace</b>")
istanbulArchaeologicalMuseum <- paste("<b>Istanbul Archaeological Museum</b>")
suleymaniye <- paste("<b>Süleymaniye Mosque</b>")
camlica <- paste("<b>Çamlıca Mosque</b>")
columnOfConstantine <- paste("<b>Column of Constantine</b>")
galataTower <- paste("<b>Galata Tower</b>")
grandBazaar <- paste("<b>Grand Bazaar</b>")
theodosianWalls <- paste("<b>Theodosian Walls</b>")
blueMosque <- paste("<b>Blue Mosque</b>")
basilicaCistern <- paste("<b>Basilica Cistern</b>")
theodosiusCistern <- paste("<b>Theodosius Cistern</b>")
maidensTower <- paste("<b>Maiden's Tower</b>")
palaceOfThePorphyrogenitus <- paste("<b>Palace of the Porphyrogenitus</b>")
princesIslands <- paste("<b>Princes' Islands</b>")
library(leaflet)
leaflet() %>% addTiles() %>%
  setView(28.990744, 41.019153, zoom = 12) %>%
  addMarkers(28.980021, 41.008484, icon = greenDotIcon, popup = hagiaSophia) %>%
  addMarkers(28.983190, 41.011348, icon = greenDotIcon, popup = topkapiPalace) %>%
    addMarkers(28.981714, 41.011651, icon = greenDotIcon, popup = istanbulArchaeologicalMuseum) %>%
    addMarkers(28.963975, 41.016290, icon = greenDotIcon, popup = suleymaniye) %>%
    addMarkers(29.070514, 41.034109, icon = greenDotIcon, popup = camlica) %>%
    addMarkers(28.971287, 41.008554, icon = greenDotIcon, popup = columnOfConstantine) %>%
    addMarkers(28.974203, 41.025628, icon = greenDotIcon, popup = galataTower) %>%
    addMarkers(28.968517, 41.010646, icon = greenDotIcon, popup = grandBazaar) %>%
    addMarkers(28.935199, 41.030083, icon = greenDotIcon, popup = theodosianWalls) %>%
    addMarkers(28.976668, 41.005431, icon = greenDotIcon, popup = blueMosque) %>%
    addMarkers(28.977818, 41.008113, icon = greenDotIcon, popup = basilicaCistern) %>%
    addMarkers(28.972425, 41.007426, icon = greenDotIcon, popup = theodosiusCistern) %>%
    addMarkers(28.940479, 41.033692, icon = greenDotIcon, popup = palaceOfThePorphyrogenitus) %>%
    addMarkers(29.004062, 41.021107, icon = greenDotIcon, popup = maidensTower) %>%
    addMarkers(29.091624, 40.875363, icon = greenDotIcon, popup = princesIslands)
```



```{r echo = FALSE, results = 'asis'}
titles <- c("Length of Stay", "Transportation", "Major Sights","Unique Foods", "Restaurant Recommendations")
values <- c("Two months", "3 hour flight from Frankfurt", "Hagia Sophia, Topkapi Palace, Istanbul Archaeological Museum, Süleymaniye, Grand Çamlıca", "Iskender kebab", "")
df <- data.frame(titles, values)
library(knitr)
kable(df, col.names = NULL)
```