---
title: "Mont-Saint-Michel, France"
---

The magnificent inspiration for the worlds of Walt Disney and Peter Jackson.

```{r out.width='100%', echo=FALSE}
abbey <- paste("<b>Abbey</b>")
laMerePoulard <- paste("<b>La Mère Poulard</b>")
library(leaflet)
leaflet() %>% addTiles() %>%
  setView(-1.511573, 48.635833, zoom = 17) %>%
  addMarkers(-1.511466, 48.635956, icon = greenDotIcon, popup = abbey) %>% # Abbey
  addMarkers(-1.511005, 48.635095, icon = greenDotIcon, popup = laMerePoulard) # La Mère Poulard
```

The Abbey, dating from the 8th century, has served as a prison and fortress in its history. Lying in the middle of a vast littoral zone, the area around the island floods with the tides.

```{r echo = FALSE, results = 'asis'}
titles <- c("Length of Stay", "Transportation", "Major Sights", "Restaurant Recommendations")
values <- c("1 day", "40 minute drive from Saint-Malo", "The Abbey", "La Mère Poulard (famous, not necessarily good)")
df <- data.frame(titles, values)
library(knitr)
kable(df, col.names = NULL)
```