---
title: "Ostend, Belgium"
---

The European port you've never heard of.

```{r out.width='100%', echo=FALSE}
fortNapoleon <- paste("<b>Fort Napoléon</b>")
cathedral <- paste("<b>Sint-Petrus-en-Pauluskerk</b>")
railwayStation <- paste("<b>Railway Station</b>")
library(leaflet)
leaflet() %>% addTiles() %>%
  setView(2.924080, 51.229326, zoom = 13) %>%
  addMarkers(2.934371, 51.238992, icon = greenDotIcon, popup = fortNapoleon) %>% # Fort Napoléon
  addMarkers(2.926140, 51.227479, icon = greenDotIcon, popup = railwayStation) %>% # Railway Station
  addMarkers(2.921210, 51.229588, icon = greenDotIcon, popup = cathedral) # Sint-Petrus-en-Pauluskerk
```

One of the largest city on the Belgian coast, Ostend was a major port in the Middle Ages, but has since been eclipsed by larger cities like Antwerp.

```{r echo = FALSE, results = 'asis'}
titles <- c("Length of Stay", "Transportation", "Major Sights","Unique Foods", "Restaurant Recommendations")
values <- c("One day", "1 hour drive from Lille", "Fort Napoléon, Sint-Petrus-en-Pauluskerk", "Filet Américain", "Charcuterie Mazère")
df <- data.frame(titles, values)
library(knitr)
kable(df, col.names = NULL)
```